### ISSUE TITLE
BLE enhancements

### ISSUE THREAD

**Issue by Kampi** [jakkra/ZSWatch#124]
Collection of different BLE topics

**ToDo**

- [x] Add timeout for enabled pairing
- [x] Fix bug with wrong JSON splitting in `ble_comm.c`
- [x] #48
- [ ] #54
- [x] #109  
- [ ] #112 
- [ ] #72
- [x] Update device information for Device Information service
- [x] Can we move all Gadgetbridge related stuff in a separate file?
- [x] Do we really need to connect and disconnect on ZBUS because apps should use Zephyr API (decide when we close the PR)?

**Open issues with notifications**

- [x] Crashing when leaving the notifications list when a notification is available
- [x] Longer notifications the body can't be seen (I guess LVGL scrolls to the bottom or something)
- [x] Sometimes the age of notification shows a huge number
- [x] Easy to accidentally remove the notification when scrolling it
- [x] Convert the age into a nice time format
- [x] Scrolling of the body field is strange
- [x] Sometimes the body field will be focused
- [x] Scrolling the notification list can be a little bit weird. I guess because of the scrolling body field. Need to check it in detail
- [ ] Hide notification popup when the app is open. Here we should think about an API to get the app status
- [ ] Notification is not 100% centered
- [ ] [Scroll one](https://docs.lvgl.io/master/overview/scroll.html#scroll-one)
- [x] Notification removal on the phone doesn´t work
- [ ] Support for YouTube notifications
- [x] Support for WhatsApp notificaitons

**Comment by Kampi** [comment]
@ldab 

I split the Gadgetbridge related code up into a separate source file.

https://github.com/jakkra/ZSWatch/tree/BLE_enhancements%23124

**Comment by ldab** [comment]
Will check the PR tomorrow 👊

**Comment by Kampi** [comment]
We are changing the communication flow for notifications to this
![image](https://github.com/jakkra/ZSWatch/assets/3458587/7c12a43e-8114-4133-97a5-0b3d574ed439)

This allows us to create and push internal notifications to the notification manager. The notification manager is the main instance in handling all notifications.

@jakkra @ldab 
I pushed the latest version of the notification rework. Feel free to test this version and give some feedback :)
Not 100% nice now, but it´s working.

**Changes so far**

- New layout
- Different icons for WhatsApp, Mail, etc.
- Title and body field
- Scrollable body (not sure if I will keep it)
- Age of the notification
- Scrolling improvement
- Notifications will be added to the notification app when the app is open

**Known changes**

- Convert the age into a nice time format
- Scrolling of the body field is strange
- Sometimes the body field will be focused
- Scrolling of the notification list can be a little bit weird. I guess because of the scrolling body field. Need to check it in detail
- Hide notification popup when the app is open. Here we should think about an API to get the app status

![image](https://github.com/jakkra/ZSWatch/assets/3458587/592667bb-d26d-451c-85ee-a884a7e58287)

**Comment by ldab** [comment]
The latest commit does not seem to build on CI, I haven’t looked as why, but is this ready to feedback?

**Comment by Kampi** [comment]
@ldab the build fails because of the style.

**Comment by jakkra** [comment]
@Kampi Running it today!
Some quick things:
- Send some notfications
  - Enter notification list
  - Exist -> crash

- Longer notifications the body can't be seen

**Comment by Kampi** [comment]
>   * Enter notification list
>   * Exist -> crash
> * Easy to accidentally remove the notification when scrolling it

@jakkra fixed :)
