### ISSUE TITLE
Clean up code base

### ISSUE THREAD

**Issue by Kampi** [jakkra/ZSWatch#90]
**ToDo**

- [x] Split up files into logical group directories
- [ ] Clean project `CMakeLists.txt` and add group `CMakeLists.txt`
- [x] Renamen `application_manager` to  `zws_application_manager`
- [x] Renamen `notification_manager` to  `zws_notification_manager`
- [x] Move display code like standby, input handling, etc. into a new `zws_display_manager` (@jakkra what do you think about it?)
- [x] Fix merge conflicts
- [x] Replace include guards with `#pragma once`
- [x] Clean up `Kconfig`
- [ ] ...

**Comment by jakkra** [comment]
> Move display code like standby, input handling, etc. into a new zws_display_manager (@jakkra what do you think

Yes totally, files prefixes with zsw and files called managers are files I have gone through and cleaned up, everything should be prefixes zsw in the future.
